gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "$"

gText_Birch_NuzlockeChallenge::
	.string "Oh, before we begin…\n"
	.string "There’s something new I’ve been\l"
	.string "researching.\p"
	.string "It’s called the NUZLOCKE CHALLENGE!\p"
	.string "It’s a special way to journey that\n"
	.string "makes your adventure more difficult\l"
	.string "and more meaningful.\p"
	.string "Under these rules, if one of your\n"
	.string "POKéMON faints, it’s considered unable\l"
	.string "to battle and must be released.\p"
	.string "Also, you may only catch the first\n"
	.string "POKéMON you encounter in each area.\p"
	.string "These rules test a TRAINER’s bond\n"
	.string "with their team.\p"
	.string "Every choice matters!\p"
	.string "So, would you like to play the\n"
	.string "NUZLOCKE CHALLENGE?\p"
	.string "$"

gText_Birch_NoNuzlocke::
	.string "That’s quite all right!\p"
	.string "There’s no shame in taking your\n"
	.string "journey at your own pace.\p"
	.string "I’ll leave the NUZLOCKE CHALLENGE\n"
	.string "disabled.\p"
	.string "If you decide you want to take on\n"
	.string "the challenge, you'll need to start\l"
	.string "a new game.\p"
	.string "$"

gText_Birch_YesNuzlocke::
	.string "I see!\n"
	.string "You’re looking for a real challenge!\p"
	.string "I’ll enable the NUZLOCKE CHALLENGE\n"
	.string "for your adventure.\p"
	.string "Take good care of your POKéMON.\n"
	.string "Every one of them will be important!\p"
	.string "$"

gText_Birch_Farewell::
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
